### ISSUE TITLE
OS X emulator broken (Frameworks corrupt) since 3.5.20

### ISSUE THREAD

**Issue by circulon** [Microsoft/BotFramework-Emulator#208]
I recently started bot development and this tools looks like the way to go for simple testing and verifying of menus and conversation flow.

Unfortunately all releases after 3.5.19 for OS X have damaged or corrupt frameworks included in the app package.
The frameworks involved are : 
Electron
Mantle
ReactiveCocoa 
Squirrel

The workaround is to additionally download the 3.5.19 version and copy the contents of frameworks folder within that app into the same place in the new app.
This shows that they are being referenced correctly but not copied or included correctly.

Could the build process be  fixed so we don't need to do this each time there is a new release.

Thanks for your help

**Comment by eanders-MS** [comment]
@circulon, what version of OS X are you running? The OS X emulator installs and runs successfully on our test Macs.

**Comment by bikasv** [comment]
Agreed. I tried 3.5.29 and 3.5.25 and both are failing on mac

**Comment by eanders-MS** [comment]
@bikasv  What version of OS X are you running?

**Comment by bikasv** [comment]
@eanders-MS It's OSX El Capitan 10.11.6

**Comment by circulon** [comment]
Tested under 10.10.5 - Opens as expected

Tested under 10.12.4 & 10.12.5 - Failed to open
Error Message - App can’t be opened because it is damage… 

Running the app from the command line provides the following error which led me to replace the Frameworks in the first place

Volumes/UData/Users/test/Downloads/botframework-emulator.app/Contents/MacOS/botframework-emulator
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/UData/Users/test/Downloads/botframework-emulator.app/Contents/MacOS/botframework-emulator
  Reason: no suitable image found.  Did find:
	/Volumes/UData/Users/test/Downloads/botframework-emulator.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
Abort trap: 6

Once the Electron Framework was replaced each of the Noted frameworks failed to load until they were replaced.

I hope this clarifies things

**Comment by eanders-MS** [comment]
Thank you for this info. It seems our Mac and Linux builds are broken or partially so in this release. We'll get it fixed in the next release.

**Comment by nwhitmont** [comment]
macOS: 10.12.5  - Emulator: 3.5.29 - works fine for me.

**Comment by arturo-cobos** [comment]
Agree. Still same problem here. 
OSX 10.12.5  on version 3.5.29

**Comment by eanders-MS** [comment]
@circulon we released emulator v3.5.31 today. Please try it out and let us know if you're able to install. Thanks!

**Comment by eanders-MS** [comment]
Closing now. If you're still seeing this problem with the new emulator, reply here and I will open.

**Comment by eheading** [comment]
Still same problem here.
OSX 10.12.6 on version 3.5.31

Originally, it said the application was broken,
After I tried xattr -rc /Applications/botframework-emulator.app
It said “Check with the developer to make sure botframework-emulator works with this version of macOS.”

May I know is there any idea?
Or any guideline that how to install it correctly on latest MacOS?
Many thanks !

**Comment by circulon** [comment]
This is Still Broken in OS X 10.12.5 & .6
The problem resides with the symlinks in the root of each of the Frameworks folders are being converted to plain files (probably during the packaging process)
Example Error
~/Desktop $ ./botframework-emulator.app/Contents/MacOS/botframework-emulator
dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/test/Desktop/./botframework-emulator.app/Contents/MacOS/botframework-emulator
  Reason: no suitable image found.  Did find:
	/Users/test/Desktop/botframework-emulator.app/Contents/MacOS/../Frameworks/ReactiveCocoa.framework/ReactiveCocoa: file too short
Abort trap: 6

-- Workaround
Relinking the files and folders foxes the issues and allows normal usage
```
cd ~/Desktop/botframework-emulator.app/Contents/Frameworks/Electron\ Framework.framework/
rm Electron\ Framework
rm Libraries
rm Resources
ln -s Versions/A/Electron\ Framework .
ln -s Versions/A/Libraries .
ln -s Versions/A/Resources .

cd ../Squirrel.framework/
rm Headers
rm Modules
rm Resources
rm Squirrel
ln -s Versions/A/Headers .
ln -s Versions/A/Modules .
ln -s Versions/A/Resources .
ln -s Versions/A/Squirrel .

cd ../ReactiveCocoa.framework/
rm Headers
rm Modules
rm ReactiveCocoa
rm Resources
ln -s Versions/A/Headers .
ln -s Versions/A/Modules .
ln -s Versions/A/Resources .
ln -s Versions/A/ReactiveCocoa .

cd ../Mantle.framework/
rm Headers
rm Mantle
rm Modules
rm Resources
ln -s Versions/A/Headers .
ln -s Versions/A/Mantle .
ln -s Versions/A/Modules .
ln -s Versions/A/Resources . 
```

**Comment by astjohn** [comment]
Still same problem here.
OSX 10.12.6 on version 3.5.31

OS simply states that the application can't be opened. Fix from @circulon and @eheading didn't seem to make a difference for me. Also couldn't open from command line.

**Comment by andriyadi** [comment]
Just sharing here. Experienced exactly the same problem today. 
After downloading the zip file, I extract with `The Unarchiver` which is somehow default on my macOS, the problem happens. Out of curiosity, I used another extracting app, in this case [`Archive Utility`](https://en.wikipedia.org/wiki/List_of_macOS_components#Archive_Utility) which is built-in macOS, now the emulator can run!

Hope it helps.

**Comment by eheading** [comment]
@andriyadi Thanks a lot ! Finally a workable solution !! I can run it on my mac now.

**Comment by eanders-MS** [comment]
@andriyadi Thank you for posting this. This has been an intractable problem for us. @astjohn, @circulon, @bikasv, @arturo-cobos does this help you?

**Comment by eanders-MS** [comment]
Closing this issue as we appear to have a solution now.

**Comment by hmontes** [comment]
Weird. This solution worked for me. Why this work instead of the unarchiver?

**Comment by storyer** [comment]
Hi guys, that's Volodymyr from the Unarchiver team. 

Indeed there's a problem, Unarchiver unpacks aliases from the archive as a regular files and thus the issue occurs. If one unpacks it with a system extraction tool, everything works perfectly. 

Moreover, we've noticed that if we'll extract archive with the system tools, than pack it again with system tools, Unarchiver can extract that archive properly.

Here we need your assistance to know more on how it was originally packed, I think that will help us a lot to locate origin of the extracting issue. I'll be looking forward for your replies.

**Comment by eanders-MS** [comment]
@storyer Thanks for posting here. We use https://github.com/electron-userland/electron-builder to build the redistributable app. I'm not familiar with its internal operation.

**Comment by iamandrewluca** [comment]
Also got this issue. I am using `brew` on macOS to install apps (maybe is using Unarchiver under the hood).  
I will try to manually download, and extract using another tool. Thanks!
```bash
brew cask install botframework-emulator
```
![image](https://user-images.githubusercontent.com/1881266/44745288-f8184780-ab0f-11e8-8ae0-b5c66f0b6cc2.png)
